name: Test

on: [ push, pull_request ]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: yarn install
        run: |
          yarn install --frozen-lockfile --network-timeout 300000

      - name: yarn package-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package-ci

# Failing because virtual framebuffer not installed
#          yarn build-e2e
#          yarn test-e2e
